### ISSUE TITLE
Recreate archive files with updated sorting

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1904]
After fixing the sorting issue described in #1900 in the development branch, the "official" archive definition files must be recreated to get the desired sorting order.

**Comment by brockho** [comment]
Maybe, I did something wrong, but after the update, I get now the following with a call of the `cocopp.archiving.create`:
```python
In [1]: import cocopp

In [2]: cocopp.archiving.create('./')
C:\Users\dimo\Anaconda3\lib\site-packages\cocopp-2.3.1.32-py3.7.egg\cocopp\archiving.py:366: UserWarning: previous definition file has been back upped to C:\Users\dimo\.cocopp\data-archives\coco.gforge.inria.fr\data-archive\._coco_archive_definition.txt_2019-07-11d22h29m55s6031754
  % backup_last_filename)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9640c44fe57f> in <module>
----> 1 cocopp.archiving.create('./')

~\Anaconda3\lib\site-packages\cocopp-2.3.1.32-py3.7.egg\cocopp\archiving.py in create(local_path)
    399         return
    400     with open(definition_file, 'wt') as file_:
--> 401         file_.write(repr(sorted(res, key=lambda s: (s.split('/')[0], s))).replace('L)', ')').replace('(', '\n('))
    402     ArchivesLocal.register(full_local_path)  # to find splattered local archives easily
    403     return COCODataArchive(full_local_path)

~\Anaconda3\lib\site-packages\cocopp-2.3.1.32-py3.7.egg\cocopp\archiving.py in <lambda>(s)
    399         return
    400     with open(definition_file, 'wt') as file_:
--> 401         file_.write(repr(sorted(res, key=lambda s: (s.split('/')[0], s))).replace('L)', ')').replace('(', '\n('))
    402     ArchivesLocal.register(full_local_path)  # to find splattered local archives easily
    403     return COCODataArchive(full_local_path)

AttributeError: 'tuple' object has no attribute 'split'
```

Python version is 3.7.3 (Anaconda) under Windows 10. Before, exactly the same call in exactly the same folder was working.

**Comment by nikohansen** [comment]
This looks like a bug and lack of test coverage. The bug should be fixed in the development branch.

**Comment by nikohansen** [comment]
The `archiving.create` function has a doctest calling `create`. How do we know that the doctests of the archiving module are executed during testing?

**Comment by nikohansen** [comment]
If you have locally a clean "official" archive and the `cocopp` installed from the development branch

```python
cocopp.archiving.create('~/.cocopp/data-archives/coco.gforge.inria.fr/data-archive')
```
creates the archive definition with the "correct" sorting. It only needs to be done for the archive root, because this is where we see the annoying sorting order of subarchives.

**Comment by brockho** [comment]
I (re-)created the archive definition file with the newest code from the development branch now and also replaced the online version of it. However, I still get the wrong sorting (after the postprocessing was adding the `url` part to my local archive definition file.

Removing the local file by hand did not help.

**Comment by nikohansen** [comment]
Could you check the third to last line when typing
```python
source(cocopp.archiving.create)
```
or
```python
cocopp.archiving.create??
```
in a Jupyter notebook?

For me it is
```python
file_.write(repr(sorted(res, key=lambda t: (t[0].split('/')[0], t))).replace('L)', ')').replace('(', '\n('))
```

**Comment by brockho** [comment]
Both code snippets give the same result for me which is the same as for you, @nikohansen.

**Comment by nikohansen** [comment]
OK, I guess then we need to see the output from

```python
cocopp.archiving.create('~/.cocopp/data-archives/coco.gforge.inria.fr/data-archive')
```
and check whether it actually re-writes the file into the `'~/.cocopp/data-archives/coco.gforge.inria.fr/data-archive'` folder and look at least at the first few lines of this file.

From the above call I get the return value
```python
['bbob/2009/ALPS_hornby_noiseless.tgz',
 'bbob/2009/AMALGAM_bosman_noiseless.tgz',
 'bbob/2009/BAYEDA_gallagher_noiseless.tgz',
 'bbob/2009/BFGS_ros_noiseless.tgz',
...
```
and the file looks like:

```python
with open('/Users/hansen/.cocopp/data-archives/coco.gforge.inria.fr/data-archive/coco_archive_definition.txt') as f: print(f.read())

[
('bbob/2009/ALPS_hornby_noiseless.tgz', '98810d28d879eb25d87949f3d7666b36f524a591e3c7d16ef89eb2caec02613b', 19150), 
('bbob/2009/AMALGAM_bosman_noiseless.tgz', 'e92951f11f8d56e0d1bdea7026bb1087142c3ea054d9e7be44fea2b063c6f394', 17020), 
('bbob/2009/BAYEDA_gallagher_noiseless.tgz', 'ed674ff71237cc020c9526b332e2d817d5cd82579920c7ff2d25ff064a57ed33', 12872), 
('bbob/2009/BFGS_ros_noiseless.tgz', 'ca9dbeab9f7ecd7d3bb39596a6835a01f832178f57add98d95592143f0095c7a', 15026), 
...
('bbob/2019/adapt-Nelder-Mead-scipy-2019_bbob_Varelas_Dahito.tgz', '0620d0cf24a8af1d217532ad2b71c778ad376f3ab652f64806995c6108fe5a41', 26485), 
('bbob/bestCustomAlg.tar.gz', '6be29bcd7a031502f770e1fa95a48fb5347f2780833a443219d2fc48ef452df8', 49), 
('bbob-biobj/2016/DEMO_Tusar_bbob-biobj.tgz', 'f1e4d3d19d5d36a88bec9916462432f297f5d5ee67ef137e685b45bbce631ed4', 9736), 
('bbob-biobj/2016/HMO-CMA-ES_Loshchilov_bbob-biobj.tgz', '07254ffa5d818298bb77714e5fb08e226e31f4da60d8500e8f00a030e2e8f530', 18876), 
...
```

**Comment by nikohansen** [comment]
Rewriting the file with `_url_` is one culprit.

**Comment by nikohansen** [comment]
The latest error (only from test branch) is
```
launching doctest (it might be necessary to close a few pop up windows to finish)
**********************************************************************
File "/root/coco/code-postprocessing/cocopp/cococommands.py", line 23, in cococommands.py
Failed example:
    path = cocopp.archives.bbob.get(4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest cococommands.py[4]>", line 1, in <module>
        path = cocopp.archives.bbob.get(4)
      File "/usr/local/lib/python3.7/dist-packages/cocopp-2.3.1.35-py3.7.egg/cocopp/archiving.py", line 668, in get
        self._download(names[0])
      File "/usr/local/lib/python3.7/dist-packages/cocopp-2.3.1.35-py3.7.egg/cocopp/archiving.py", line 685, in _download
        self.check_hash(full_name)
      File "/usr/local/lib/python3.7/dist-packages/cocopp-2.3.1.35-py3.7.egg/cocopp/archiving.py", line 829, in check_hash
        '' % (name, self.full_path(name)))
    ValueError: wrong checksum for "/root/.cocopp/data-archives/coco.gforge.inria.fr/data-archive/bbob/bbob/2009/BIPOP-CMA-ES_hansen_noiseless.tgz". Consider to (re)move file
       /root/.cocopp/data-archives/coco.gforge.inria.fr/data-archive/bbob/bbob/2009/BIPOP-CMA-ES_hansen_noiseless.tgz
    as it may be a partial or unsuccessful download.
    A missing file will be downloaded again by `get`.
    Alternatively, call `update` to update definitions
    and checksums and allow for automatic re-downloads.
    If this is not a remote archive consider to re-`create` it.
```
suggesting a mistake when creating the path `...data-archive/bbob/bbob/2009/...`.

**Comment by nikohansen** [comment]
I can reproduce the following error locally when I used `update_all`:
```python
import doctest
import cocopp
cocopp.archives.update_all()
doctest.testmod(cocopp.archiving)
```
```
in cocopp.archiving.COCOBBOBBiobjDataArchive
Failed example:
    bbob.index('2009/CMA-ESPLUSSEL_auger_noiseless.tgz')  # just list.index
Exception raised:
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest cocopp.archiving.COCOBBOBBiobjDataArchive[13]>", line 1, in <module>
        bbob.index('2009/CMA-ESPLUSSEL_auger_noiseless.tgz')  # just list.index
    ValueError: '2009/CMA-ESPLUSSEL_auger_noiseless.tgz' is not in list
```

**Comment by nikohansen** [comment]
The uploaded definition files are wrong. For example, the file `https://coco.gforge.inria.fr/data-archive/bbob/coco_archive_definition.txt` contains entries
```
[
('bbob/2009/ALPS_hornby_noiseless.tgz', '98810d28d879eb25d87949f3d7666b36f524a591e3c7d16ef89eb2caec02613b', 19150), 
('bbob/2009/AMALGAM_bosman_noiseless.tgz', 'e92951f11f8d56e0d1bdea7026bb1087142c3ea054d9e7be44fea2b063c6f394', 17020), 
...
```
with additional leading ``bbob/`. This should not be the case if it was created like
```python
cocopp.archiving.create('~/.cocopp/data-archives/coco.gforge.inria.fr/data-archive/bbob')
```

**Comment by nikohansen** [comment]
Code to create the correct archive definition files if the full clean archive is on the local disk:
```python
import cocopp
cocopp.archives.add_archive('bbob-largescale')  # is not yet there by default
for name in cocopp.archives.names:
    print(name)
    cocopp.archiving.create('~/.cocopp/data-archives/coco.gforge.inria.fr/data-archive/' + 
                            (name if name != 'all' else ''))
```

**Comment by nikohansen** [comment]
I uploaded the fixed definitions files which seem to be in sync with the online data, so the issue seem to be solved.
